version: '3'
services:

  ts-cypht:
    image: tailscale/tailscale:latest
    container_name: ts-cypht
    hostname: cypht
    environment:
      - TS_AUTHKEY=tskey-auth-ksRATgZYQu11CNTRL-YQfLLuQ2hJVTgYuhr2NJJVL1ekQUCVZh
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${PWD}/ts-cypht/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  db:
    image: mariadb:10
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=cypht
      - MYSQL_USER=cypht
      - MYSQL_PASSWORD=cypht_password
  cypht:
    image: sailfrog/cypht-docker:latest
    volumes:
      - ./cypht/users:/var/lib/hm3/users
    # ports:
    #   - "80:80"
    environment:
      - CYPHT_AUTH_USERNAME=admin
      - CYPHT_AUTH_PASSWORD=qwfqwf
      - CYPHT_DB_CONNECTION_TYPE=host
      - CYPHT_DB_HOST=db
      - CYPHT_DB_NAME=cypht
      - CYPHT_DB_USER=cypht
      - CYPHT_DB_PASS=cypht_password
      - CYPHT_SESSION_TYPE=DB
    network_mode: service:ts-cypht
    depends_on: 
      - ts-cypht
